### ISSUE TITLE
virtualenv: no such option -r

### ISSUE THREAD

**Issue by quenenni** [pcolmant/repanier#13]
On a brand new debian 9, I tried the command:
`
virtualenv -p python3 venv . venv/bin/activate pip install -r requirements/requirement.tx
`
and got the error:
`
virtualenv: error: no such option: -r
`
And indeed, a 'man virtualenv' shows no -r option (and no other option regarding requirements).

What can I do?

Thanks

----
python3  ->                      3.5.3-1
python-virtualenv  ->                            15.1.0+ds-1 
python3-virtualenv   ->                         15.1.0+ds-1
virtualenv      ->                              15.1.0+ds-1

**Comment by pcolmant** [comment]
Hi Que nenni,

Sorry, there was a formating issue on the readme.
The french written part of the readme is a temporary work in progress.
Would you like to try Repanier as a GAS group, as a GASAP group (with contracts) or as a producer (with boxes), or as all ?

Kr,

Patrick

**Comment by quenenni** [comment]
Salut Patrick,

On peut continuer en français en fait.

Je suis occupé à essayer d'installer repanier sur un nouveau serveur pour proposer aux gasap bxlois de tester repanier et de le mettre en place pour tous les gasap qui le souhaite s'ils sont contents avec cet outil.

Le truc est que Python n'est pas mon forté. Je ne sais donc pas trop où aller voir pour ce problème.

Si j'ai bien compris, il faut créer un environnement virtuel pythonesque dans lequel il doit installer toutes les dépendances inclues dans le fichier requirements.
Y a-t'il un autre moyen d'arriver à ça?

Aussi, est-ce bien virtualenv qui est censé récupérer et installer la liste des requirements ou bien est la commande pip dans l'environnement virtuel qui doit récupérer et installer les dépendances?

**Comment by quenenni** [comment]
Re-bonjour..

Mon collègue me dit qu'on a rdv ensemble demain ensemble :)
Je vais être à ce rdv pour discuter avec toi des soucis que j'ai.

En attendant, voici qqes remarques par rapport à la procédure d'installation:

En effet, la version fr du tuto est pas top du tout. J'ai suivi la version en. Peut-être ne pas afficher la version fr tant qu'elle n'est pas complète.

(NB: j'ai créé le projet avec la commande "django-admin.py startproject website", mes dossiers se nomment donc website dans ~/venv/)

1. Postgresql était déjà installé quand j'ai lancé la commande "dpkg-reconfigure locales". Cela génère une erreur à la commande 
`CREATE DATABASE db_name WITH TEMPLATE = template0 OWNER = db_user ENCODING = 'UTF8' LC_COLLATE = 'fr_BE.UTF-8' LC_CTYPE = 'fr_BE.UTF-8';`
Une erreur liée à l'encoding qui n'est pas reconnu.
-> La solution est de redémarrer postgresql pour qu'il prenne en compte la reconfiguration des locales.

2. \# ----------------- Create django file session directory

Il manque la ligne "mkdir /var/tmp/django-session" juste après

3. \# now : copy from gihub/pcolmant/repanier/mysite/media/... to ~/venv/my_web_site/my_web_site/media/

Le dossier d'origine n'existe pas. J'ai trouvé celui-ci à la place:
github/pcolmant/repanier/repanier/static/

4. \# now : copy from gihub/pcolmant/repanier/mysite/... to ~/venv/my_web_site/my_web_site/

 - le dossier locale -> ok
 - les fichiers common-settings / urls.py et wsgi.py -> trouvés mais existent aussi à la destination -> faut-il écraser les fichiers dans le dossier de destination?
- le fichier my_web_site.ini -> n'existe pas. J'ai trouvé le fichier mysite.ini que j'ai copié à la place.
Mais suis-je censé le renommer avec le même nom que mon projet?

(suis-je donc censé le renommer website.ini?  Y a déjà un fichier website.ini dans ce dossier '~/venv/website/website/', fichier qui a été créé et remplit avec les données mise dans le tuto, et le fichier mysite.ini a des settings manquants et des valeurs génériques contrairement au fichier que j'ai crée manuellement)

5. \# now : copy from gihub/pcolmant/repanier to ~/venv/my_web_site/

 - manage.py -> trouvé mais existe déjà dans le dossier de destination. Faut-il l'écraser?

6. python manage.py collectstatic

Et ici, ça bloque.

J'ai trouvé 2 fichiers manage.py
~/venv/website/manage.py
~/venv/website/repanier/manage.py

Si je me place dans le dossier ~/venv/website/ (c'est le manage.py que j'ai copié du dossier de github), la commande renvoie cette erreur:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/pi/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/venv/website/website/common_settings.py", line 12, in <module>
    from repanier.const import *
ImportError: No module named 'repanier.const'
```
L'erreur indique qu'il ne trouve pas de ss-dossiers repanier et dedans un fichier const.

Si je me place dans le dossier ~/venv/website/repanier/, il y a bien un dossier repanier avec un fichier const d-edans. La commande renvoie cette erreur-ci:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/home/pi/venv/lib/python3.5/collections/__init__.py", line 881, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/pi/venv/lib/python3.5/collections/__init__.py", line 873, in __missing__
    raise KeyError(key)
KeyError: 'django_settings_group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/pi/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/pi/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/venv/website/repanier/mysite/common_settings.py", line 88, in <module>
    DJANGO_SETTINGS_GROUP = config.getboolean('DJANGO_SETTINGS', 'DJANGO_SETTINGS_GROUP')
  File "/usr/lib/python3.5/configparser.py", line 826, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'django_settings_group' in section: 'DJANGO_SETTINGS'
```

Il semblerait qu'il ne trouve pas la variable django_settings_group'

J'ai fouillé les différents fichiers .ini. Dans celui que j'ai créé manuellement, cette variable est bien définie, mais pas dans les 2 autres que j'ai trouvé:
 - ~/venv/website/repanier./website/website.ini -> celui que j'ai créé manuellement
 - ~/venv/website/repanier/repanier/mysite/mysite.ini & ~/venv/website/repanier/website/mysite.ini -> recopié du dossier github, mais n'ont pas toutes les option et les valeurs ne sont pas top (sqlite définit au lieu de postgrsql par ex).

J'ai concaténé mon fichier ini créé avec les 2 autres et mis les bonnes valeurs aux options.
En relançant la commande 'python manage.py collectstatic', j'ai maintenant l'erreur:
```
##################################
relation "repanier_configuration" does not exist
LINE 1: ...epanier_configuration"."email_host_password" FROM "repanier_...
                                                             ^

##################################
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/pi/venv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/home/pi/venv/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/home/pi/venv/lib/python3.5/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/home/pi/venv/lib/python3.5/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "/home/pi/venv/lib/python3.5/site-packages/django/core/files/storage.py", line 397, in listdir
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/venv/website/repanier/collect-static'
```

Et là, j'ai abandonné car j'ai l'impression de m'enfoncer dans qqch que je ne maîtrise pas.

Aurais-tu une idée du problème?
