### ISSUE TITLE
erreur à l'installation: collectstatic - Missing staticfiles manifest entry

### ISSUE THREAD

**Issue by berteh** [pcolmant/repanier#17]
merci pour l'effort pour l'amélioration de la documentation d'installation.

dans l'étape [install-or-update-repanier](https://github.com/pcolmant/repanier#install-or-update-repanier) la collection des ressources statiques échoue pour moi avec le message suivant:
    

```
~/prd1/_0_prd_example$ python manage.py collectstatic

Traceback (most recent call last):
  File "/home/berteh/prd1/_0_prd_example/repanier/big_blind_static.py", line 18, in url
    return super(ManifestStaticFilesStorage, self).url(context, True)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'djangocms_text_ckeditor/js/dist/bundle-bca0d2d3f4.cms.ckeditor.min.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/berteh/prd1/_0_prd_example/repanier/big_blind_static.py", line 22, in url
    return super(ManifestStaticFilesStorage, self).url(new_context, True).replace(__version__, "")
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'djangocms_text_ckeditor/js/dist/3.5.2/bundle-bca0d2d3f4.cms.ckeditor.min.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/berteh/prd1/_0_prd_example/repanier/big_blind_static.py", line 27, in url
    return super(ManifestStaticFilesStorage, self).url(context, True)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 162, in url
    return self._url(self.stored_name, name, force)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 141, in _url
    hashed_name = hashed_name_func(*args)
  File "/home/berteh/prd1/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 432, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'djangocms_text_ckeditor/js/dist/bundle-45a646fecc.cms.ckeditor.min.js'

```

Le fait d'ajuster les options suivantes dans `settings.ini` ne résoud pas le soucis, contrairement aux suggestions de https://docs.djangoproject.com/en/1.11/howto/static-files/ ou https://stackoverflow.com/questions/44160666/valueerror-missing-staticfiles-manifest-entry-for-favicon-ico

```
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collect-static')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
#STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
```

Comment corriger ce problème qui empeche la collection des ressources statiques?... et toute autre exécution de `manage.py` d'ailleurs.

Merci,
Berteh.

**Comment by pcolmant** [comment]
Please, use the latest version of Repanier where a workaround is now present waiting for a solution in djangocms-text-ckeditor : https://github.com/divio/djangocms-text-ckeditor/issues/474

**Comment by berteh** [comment]
Thanks. your workaround did indeed fix the missing manifest error.
