### ISSUE TITLE
Faciliter les contributions

### ISSUE THREAD

**Issue by ghost** [pcolmant/repanier#2]
Les contributions à répanier pourraient être plus immédiates et intuitives pour les nouveaux développeurs, les designeurs et les traducteurs. Je pense principalement à améliorer la documentation et à simplifier l'environnement de développement (sqlite, …). On pourrait aussi fournir un jeu de valeurs tests (utilisateurs et données fictives)

**Comment by ghost** [comment]
sqlite comme choix de base-de-données #5

**Comment by hellekin** [comment]
Salut, suite à une conversation avec Florian j'ai tenté d'installer l'application. Je reproduis ici les étapes nécessaires -- certaines non-documentées -- pour arriver au point où je bute.

## Obtenir le code
```
git clone https://github.com/pcolmant/repanier
cd repanier
```
## Préparer le code

2 étapes : créer l'environnement virtuel et l'activer, puis activer le code.

Pour la première étape, j'utilise `mkvirtualenv -p /usr/bin/python3 repanier; workon repanier` mais l'usage canonique de `virtualenv` fonctionne de la même manière.

La seconde étape est plus délicate car il faut passer par une lecture du code pour pouvoir créer la base de données : en effet, il n'est pas indiqué qu'un fichier doit être créé en fonction du nom du répertoire dans lequel on a cloné l'application. Dans mon cas -- et probablement celui de beaucoup de potentiels contributeurs :  `repanier`. Il faut donc copier le fichier d'initialisation au bon endroit : 

```
cp mysite/mysite.ini repanier.ini
```

Ensuite reprendre le cheminement normal : 

```
./manage.py migrate
./manage.py loaddata fixtures/initial_users.yaml
```

## Lancer l'application

```
./manage.py runserver
##################################
no such table: repanier_configuration
##################################
##################################
no such table: repanier_configuration
##################################
Performing system checks...

System check identified no issues (0 silenced).
October 11, 2017 - 11:59:41
Django version 1.10.7, using settings 'mysite.common_settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

C'est là que le bât blesse : il semble qu'il manque une ou des migrations. Lorsque j'essaie de me connecter à l'admin (avec **admin:secret**), je reçois une erreur: **A server error occurred.  Please contact the administrator.**

```
[11/Oct/2017 12:00:47] "GET / HTTP/1.1" 302 0
[11/Oct/2017 12:00:47] "GET /fr/ HTTP/1.1" 200 2645
[11/Oct/2017 12:00:47] "GET /static/cms/css/3.4.4/cms.base.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/cms/css/3.4.4/cms.welcome.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/cms/img/favicon.png HTTP/1.1" 200 10311
[11/Oct/2017 12:00:47] "GET /static/cms/fonts/3.4.4/django-cms-iconfont.woff2 HTTP/1.1" 200 4964
[11/Oct/2017 12:00:47] "GET /static/cms/fonts/src/logo.svg HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /fr/coordi/login/?next=/fr/?edit HTTP/1.1" 200 6293
[11/Oct/2017 12:00:47] "GET /static/cms/fonts/3.4.4/django-cms-iconfont.woff HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/djangocms_admin_style/css/djangocms-admin.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/djangocms_admin_style/js/dist/bundle.adminstyle.min.js HTTP/1.1" 304 0
[11/Oct/2017 12:00:47] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[11/Oct/2017 12:00:58] "POST /fr/coordi/login/?next=/fr/?edit HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: repanier_customer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
    response = response_for_exception(request, exc)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
    response = get_response(request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 377, in login
    return login(request, **defaults)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/auth/views.py", line 47, in inner
    return func(*args, **kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/auth/views.py", line 81, in login
    if form.is_valid():
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/forms/forms.py", line 169, in is_valid
    return self.is_bound and not self.errors
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/forms/forms.py", line 161, in errors
    self.full_clean()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/forms/forms.py", line 371, in full_clean
    self._clean_form()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/forms/forms.py", line 398, in _clean_form
    cleaned_data = self.clean()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/auth/forms.py", line 191, in clean
    self.user_cache = authenticate(username=username, password=password)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/home/hellekin/src/vendor/repanier/repanier/auth_backend.py", line 37, in authenticate
    ).order_by('?').first()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/models/query.py", line 556, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hellekin/.virtualenvs/repanier/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: repanier_customer
```

**Comment by pcolmant** [comment]
Could you check if the actual procedure "How to install..." on https://github.com/pcolmant/repanier solve this issue ?

**Comment by pcolmant** [comment]
Entre temps @hellekin  et moi avons mis à jour le readme du projet et testé la procédure d'installation.
